// demos/tidelight/gen-assets.ts — the game's content pipeline: every backdrop
// and portrait is generated by the PixelLab pixel-art API (pixellab.ai) from
// the seeded manifest below, then normalized into the pak-safe PNG subset.
//
//   bun demos/tidelight/gen-assets.ts             # generate missing assets
//   bun demos/tidelight/gen-assets.ts --force     # regenerate everything
//   bun demos/tidelight/gen-assets.ts --only=face-maren.png
//
// Auth: PIXELLAB_API_KEY in the repo root .env (Bun auto-loads .env from the
// cwd; the manual parse below keeps the script cwd-independent). Every entry
// pins a `seed` — PixelLab derives its starting noise from it, so a re-run
// reproduces the same art. Generated files are committed; existing files are
// skipped, which makes the script a cheap no-op unless you delete an asset or
// pass --force.
//
// Portrait "state" variants (WICK's alert eye, Maren by the fire) are made
// with init_image + a shifted description, so a character keeps its identity
// across moods — the same trick at generation time that Detroit-style story
// UIs pull off with actor performances.
//
// Output discipline: PixelLab answers 8-bit RGBA non-interlaced PNGs, which
// compiler/pak.ts decodePng already accepts — but we still decode + re-encode
// through the exact canonical subset the gallery baker writes (colorType 6,
// bit depth 8, filter 0, single node:zlib IDAT) so the committed bytes are
// deterministic and the pak build can never hit an exotic encoder feature.
// Texture sizes are pow2 (256x128 scenes, 64x64 portraits) per DESIGN.md.

import { existsSync } from "node:fs";
import { deflateSync } from "node:zlib";
import { decodePng } from "../../compiler/pak.ts";

const HERE = new URL(".", import.meta.url).pathname; // demos/tidelight/
const ROOT = new URL("../..", import.meta.url).pathname; // PocketJS/
const API = "https://api.pixellab.ai/v1";

// ---------------------------------------------------------------------------
// The manifest — one entry per committed asset
// ---------------------------------------------------------------------------

interface Asset {
  name: string;
  prompt: string;
  w: number;
  h: number;
  seed: number;
  /** Transparent background (portraits). */
  transparent?: boolean;
  outline?: string;
  shading?: string;
  detail?: string;
  /** Derive from a previously generated asset (identity-preserving variant). */
  initFrom?: string;
  /** init_image influence 1..999 (PixelLab default 300). */
  initStrength?: number;
}

const SCENE = { w: 256, h: 128 }; // pow2; drawn at 480x240 (uniform 1.875x)
const FACE = { w: 64, h: 64 }; // pow2; drawn 1:1

const ASSETS: Asset[] = [
  {
    name: "bg-title.png",
    prompt:
      "lonely lighthouse on a black rock headland at night, lamp beam sweeping over a dark stormy sea, " +
      "heavy clouds, faint rain, deep blue and cyan palette, moody pixel art seascape",
    ...SCENE,
    seed: 101,
    shading: "detailed shading",
    detail: "highly detailed",
  },
  {
    name: "bg-shore.png",
    prompt:
      "rocky shore below a lighthouse at night in a storm, waves crashing over dark rocks, " +
      "wreck debris and a collapsed figure washed up on the stones, cold teal and slate palette, " +
      "beam of lighthouse light across the foreground, moody pixel art",
    ...SCENE,
    seed: 102,
    shading: "detailed shading",
    detail: "highly detailed",
  },
  {
    name: "bg-lamproom.png",
    prompt:
      "inside a lighthouse lamp room at night, giant brass fresnel lens lamp glowing warm, " +
      "brass machinery and railings, rain streaking the tall windows, dark storm outside, " +
      "warm amber glow against deep blue night, pixel art interior",
    ...SCENE,
    seed: 103,
    shading: "detailed shading",
    detail: "highly detailed",
  },
  {
    name: "bg-quarters.png",
    prompt:
      "lighthouse keeper quarters interior at night, small iron stove with fire glow, " +
      "wooden cot with wool blankets, oil lamp on a table, rope and charts on the wall, " +
      "storm rain on a small round window, warm amber on dark brown, cozy grim pixel art interior",
    ...SCENE,
    seed: 104,
    shading: "detailed shading",
    detail: "highly detailed",
  },
  {
    name: "bg-storm.png",
    prompt:
      "lighthouse tower exterior in a violent night storm, lamp dark and unlit at the top, " +
      "huge waves striking the rocks, lightning flash, driving rain streaks, " +
      "desperate cold palette of slate and white foam, dramatic pixel art",
    ...SCENE,
    seed: 105,
    shading: "detailed shading",
    detail: "highly detailed",
  },
  {
    name: "bg-barge.png",
    prompt:
      "grey dawn at a stone pier below a lighthouse, iron government barge ship approaching " +
      "through cold fog, flat calm sea after a storm, muted grey blue palette, " +
      "quiet ominous pixel art seascape",
    ...SCENE,
    seed: 106,
    shading: "medium shading",
    detail: "highly detailed",
  },
  {
    name: "face-wick.png",
    prompt:
      "weathered brass lighthouse automaton head, glowing cyan lamp eye, pixel art portrait",
    ...FACE,
    seed: 7, // the very first pipeline test image — kept, it set WICK's look
    transparent: true,
  },
  {
    name: "face-wick-alert.png",
    prompt:
      "weathered brass lighthouse automaton head, glowing red alarm eye, warning state, " +
      "pixel art portrait",
    ...FACE,
    seed: 8,
    transparent: true,
    initFrom: "face-wick.png",
    initStrength: 400,
  },
  {
    name: "face-maren.png",
    prompt:
      "young woman with wet dark hair plastered to her face, soaked grey army greatcoat, " +
      "exhausted pale face, wary eyes, pixel art portrait, cold light",
    ...FACE,
    seed: 201,
    transparent: true,
  },
  {
    name: "face-maren-warm.png",
    prompt:
      "young woman with drying dark hair, grey army greatcoat open over a wool blanket, " +
      "tired faint smile, warm firelight on her face, pixel art portrait",
    ...FACE,
    seed: 202,
    transparent: true,
    initFrom: "face-maren.png",
    initStrength: 350,
  },
  {
    name: "face-halloway.png",
    prompt:
      "stern old harbor inspector, dark uniform cap with brass badge, grey mustache, " +
      "cold pale eyes, black oilskin coat, pixel art portrait",
    ...FACE,
    seed: 301,
    transparent: true,
  },
  {
    name: "face-wire.png",
    prompt:
      "brass marine radio wall unit, round speaker grille, single glowing amber dial, " +
      "bakelite switches, pixel art object on dark",
    ...FACE,
    seed: 302,
    transparent: true,
  },
];

// ---------------------------------------------------------------------------
// Canonical PNG encoder (identical subset to demos/gallery/gen-assets.ts,
// validated against compiler/pak.ts decodePng: colorType 6, bitDepth 8,
// filter 0, single IDAT)
// ---------------------------------------------------------------------------

const CRC = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; t[n] = c >>> 0; }
  return t;
})();
function crc32(buf: Uint8Array): number { let c = 0xffffffff; for (let i = 0; i < buf.length; i++) c = CRC[(c ^ buf[i]) & 255] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; }
function u32be(n: number): Uint8Array { const b = new Uint8Array(4); new DataView(b.buffer).setUint32(0, n >>> 0, false); return b; }
function chunk(type: string, data: Uint8Array): Uint8Array {
  const tb = new TextEncoder().encode(type);
  const body = new Uint8Array(tb.length + data.length); body.set(tb, 0); body.set(data, tb.length);
  const out = new Uint8Array(4 + body.length + 4);
  out.set(u32be(data.length), 0); out.set(body, 4); out.set(u32be(crc32(body)), 4 + body.length);
  return out;
}
function encodePng(w: number, h: number, rgba: Uint8Array): Uint8Array {
  const stride = w * 4;
  const raw = new Uint8Array((stride + 1) * h);
  for (let y = 0; y < h; y++) { raw[y * (stride + 1)] = 0; raw.set(rgba.subarray(y * stride, y * stride + stride), y * (stride + 1) + 1); }
  const ihdr = new Uint8Array(13); const dv = new DataView(ihdr.buffer);
  dv.setUint32(0, w, false); dv.setUint32(4, h, false); ihdr[8] = 8; ihdr[9] = 6;
  const idat = new Uint8Array(deflateSync(raw));
  const sig = new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10]);
  const parts = [sig, chunk("IHDR", ihdr), chunk("IDAT", idat), chunk("IEND", new Uint8Array(0))];
  const total = parts.reduce((n, p) => n + p.length, 0); const out = new Uint8Array(total);
  let o = 0; for (const p of parts) { out.set(p, o); o += p.length; } return out;
}

// ---------------------------------------------------------------------------
// PixelLab client
// ---------------------------------------------------------------------------

function apiKey(): string {
  const env = process.env.PIXELLAB_API_KEY;
  if (env) return env;
  const envPath = ROOT + ".env";
  if (existsSync(envPath)) {
    const text = require("node:fs").readFileSync(envPath, "utf8") as string;
    const m = text.match(/^PIXELLAB_API_KEY=["']?([^"'\n]+)["']?$/m);
    if (m) return m[1];
  }
  throw new Error("tidelight: PIXELLAB_API_KEY not set (repo .env or environment)");
}

async function generate(key: string, asset: Asset): Promise<Uint8Array> {
  const body: Record<string, unknown> = {
    description: asset.prompt,
    image_size: { width: asset.w, height: asset.h },
    text_guidance_scale: 8,
    no_background: asset.transparent ?? false,
    seed: asset.seed,
  };
  if (asset.outline) body.outline = asset.outline;
  if (asset.shading) body.shading = asset.shading;
  if (asset.detail) body.detail = asset.detail;
  if (asset.initFrom) {
    const initPath = HERE + asset.initFrom;
    if (!existsSync(initPath)) throw new Error(`tidelight: init image ${asset.initFrom} missing — order the manifest base-first`);
    const bytes = new Uint8Array(await Bun.file(initPath).arrayBuffer());
    body.init_image = { type: "base64", base64: Buffer.from(bytes).toString("base64") };
    body.init_image_strength = asset.initStrength ?? 300;
  }

  for (let attempt = 1; ; attempt++) {
    const res = await fetch(`${API}/generate-image-pixflux`, {
      method: "POST",
      headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
      body: JSON.stringify(body),
    });
    if (res.status === 429 && attempt <= 3) {
      console.log(`  rate limited, retry ${attempt}/3 in 5s ...`);
      await Bun.sleep(5000);
      continue;
    }
    if (!res.ok) {
      const detail = await res.text();
      throw new Error(`tidelight: pixellab ${res.status} for ${asset.name}: ${detail.slice(0, 300)}`);
    }
    const json = (await res.json()) as { image: { base64: string } };
    return Uint8Array.from(Buffer.from(json.image.base64, "base64"));
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const force = process.argv.includes("--force");
  const only = process.argv.find((a) => a.startsWith("--only="))?.slice("--only=".length);
  const key = apiKey();

  let generated = 0;
  let skipped = 0;
  for (const asset of ASSETS) {
    const path = HERE + asset.name;
    if (only && asset.name !== only) continue;
    if (existsSync(path) && !force && !only) {
      skipped++;
      continue;
    }
    const t0 = Date.now();
    const png = await generate(key, asset);
    const img = decodePng(png); // validate against the pak decoder's subset
    if (img.width !== asset.w || img.height !== asset.h) {
      throw new Error(`tidelight: ${asset.name} came back ${img.width}x${img.height}, wanted ${asset.w}x${asset.h}`);
    }
    await Bun.write(path, encodePng(img.width, img.height, img.rgba));
    generated++;
    console.log(`  generated ${asset.name}  ${asset.w}x${asset.h} seed ${asset.seed}  (${((Date.now() - t0) / 1000).toFixed(1)}s)`);
  }

  const bal = await fetch(`${API}/balance`, { headers: { Authorization: `Bearer ${apiKey()}` } })
    .then((r) => (r.ok ? r.json() : null))
    .catch(() => null);
  console.log(
    `tidelight: ${generated} generated, ${skipped} kept` +
      (bal && typeof (bal as { usd?: number }).usd === "number" ? `  (pixellab balance: $${(bal as { usd: number }).usd})` : ""),
  );
}

await main();
